### ISSUE TITLE
Make run_sh, exec work with docker images that do not contain a shell

### ISSUE THREAD

**Issue by tedim52** [kurtosis-tech/kurtosis#1859] opened 2023-11-27 16:29 UTC
### Background & motivation

Currently, doing a `run_sh` and an `exec` on a docker image without shell on it is not possible because these instructions call `bin/sh` under the hood.

### Desired behaviour

Able to use `run_sh` or `exec` on docker images without a shell.

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by h4ck3rk3y** [comment] 2023-11-27 17:00
This is a dupe of https://github.com/kurtosis-tech/kurtosis/issues/1845; close one of them?

**Comment by leeederek** [comment] 2023-12-05 13:15
Closing in favor of #1845

**Closed as completed by leeederek** 2023-12-05 13:15 UTC
Labels: feature request, painful, cli
