### ISSUE TITLE
stream running logs during enclave creation even if it fails

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#1512] opened 2023-10-10 15:12 UTC
### What's your CLI version?

0.84.3

### Description & steps to reproduce

Tried running https://github.com/galenmarchetti/basic-service-package

The images weren't available for amd64 at the time; the cloud UI just kept spinning and didn't say what happened. Refreshing it led to an empty enclave with no services and just the first files artifact

### Desired behavior

logs should be streamed even if enclave creation / run fails at any step

### What is the severity of this bug?

Critical; I am blocked and Kurtosis is unusable for me because of this bug.

### What area of the product does this pertain to?

Frontend(Cloud): the Graphical User Interface, including the Enclave Manager

**Comment by mieubrisse** [comment] 2023-10-12 01:41
I thiiiink @tedim52 or @adschwartz is going to take this one

**Comment by adschwartz** [comment] 2023-10-12 12:56
@mieubrisse Yes, I'm working this.

**Comment by adschwartz** [comment] 2023-10-12 20:39
@h4ck3rk3y I tried running the package above but wasn't able to reproduce (as expected since you now have those images). Another idea for reproducing was to run Laurent's etcd package and give it a bad image but that also failed as expected without hanging. Do you have another idea for how I can reproduce this issue?

**Comment by h4ck3rk3y** [comment] 2023-10-13 12:47
You can replace the images with galenmarchetti/service-a, `galenmarchetti/service-a`  and galenmarchetti/service-a  and see how that works!

**Comment by mieubrisse** [comment] 2024-02-27 03:40
@h4ck3rk3y @adschwartz are we good to close this?

**Comment by adschwartz** [comment] 2024-02-27 16:44
@mieubrisse Yes we did get to the bottom of this. The underlying issue with this was that the downloading of the images took a long time, making the stream connection drop. We've since increased it. Of course that's not going to solve things perfectly but it makes it less _likely_ that they will happen again.

**Closed as completed by adschwartz** 2024-02-27 16:44 UTC
Labels: bug, critical, frontend
