### ISSUE TITLE
JSON decode on run_sh output

### ISSUE THREAD

**Issue by xavier-romero** [kurtosis-tech/kurtosis#2434] opened 2024-05-07 18:42 UTC
### What's your CLI version?

0.89.3

### Description & steps to reproduce

By running that plan:
```
def run(plan):
    x = plan.run_sh(
        run="""
        echo '{"key":"value"}'
        """
    )
    a = x.output
    plan.print(a)
    plan.print(a[:])
    plan.print(a[0:-1])
    plan.print(a[0:-1]+a[-1])
```

I get these outputs:
```
{"key":"value"}
{"key":"value"}
{{kurtosis:b0597720154d47fc9701d3bec6c15dc2:output.runtime_value}
{"key":"value"}
```
Specially surprised with the 4th result not being like the 3rf tbh ':--o

When trying to decode json output like this:
```
def run(plan):
    x = plan.run_sh(
        run="""
        echo '{"key":"value"}'
        """
    )
    a = x.output
    json.decode(a)
```
I get an error:
`Evaluation error: json.decode: at offset 2, unexpected character 'k'`

For some reason when trying to decode it's using that internal reference instead of the resulting string.

### Desired behavior

To decode the output string instead of the internal object reference.

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

### What area of the product does this pertain to?

CLI: the Command Line Interface

**Comment by laurentluce** [comment] 2024-05-13 22:31
@tedim52 explained to me that Starlark cannot interpret string slices.  All the `print` commands operate on the full `a` output except the third one so the result is expected.

**Comment by laurentluce** [comment] 2024-05-13 22:33
A future reference cannot be decoded so the exact output will have to be returned as part of `plan.run_sh` with the help of `jq` for example.

**Comment by laurentluce** [comment] 2024-05-13 22:34
We are aware that future reference / string manipulation is not great today.

**Comment by laurentluce** [comment] 2024-05-13 22:37
Duplicate of #2049

**Closed as completed** 2024-05-13 22:38 UTC
Labels: bug, painful, cli
