### ISSUE TITLE
explore ways of making port forwarding optional and add a flag to switch it off

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/kurtosis#1184] opened 2023-08-29 09:12 UTC
### Background & motivation

PortForwarding can take a while and isn't necessary for everyone using the package.

### Desired behaviour

Add an ability to the gateway or the cli to switch off port forwards

### How important is this to you?

Painful; the lack of this feature makes using Kurtosis frictionful.

**Comment by laurentluce** [comment] 2023-09-06 14:21
Duplicate of #1236

**Closed as not planned by laurentluce** 2023-09-06 14:21 UTC
Labels: feature request, painful
