### ISSUE TITLE
Unable to remove enclave

### ISSUE THREAD

**Issue by barnabasbusa** [kurtosis-tech/kurtosis#842] opened 2023-07-07 14:01 UTC
### What's your CLI version?

0.80.7

### Description & steps to reproduce

I have tried to stop and force remove an enclave `kurtosis enclave rm 3afd98ccccdb -f`
```shell
INFO[2023-07-07T15:49:11+02:00] Destroying enclaves...                       
Error:  An error occurred running command 'rm'
  Caused by: An error occurred calling the run function for command 'rm'
  Caused by: One or more errors occurred destroying the enclaves:
  >>>>>>>>>>>>>>>>> 3afd98ccccdb <<<<<<<<<<<<<<<<<
  An error occurred destroying enclave '3afd98ccccdb'
  Caused by: An error occurred destroying enclave with identifier '3afd98ccccdb'
  Caused by: rpc error: code = Unknown desc = An error occurred destroying enclave with identifier '3afd98ccccdb':
  Caused by: An error occurred removing enclave network with ID 'acf219c71a72360caf7bce311a2955d4a345be265756b01604a5bca50d9a4fc8'
  Caused by: An error occurred removing the Docker network with ID acf219c71a72360caf7bce311a2955d4a345be265756b01604a5bca50d9a4fc8
  Caused by: Error response from daemon: error while removing network: network 3afd98ccccdb4e718121ca5c1be521a0 id acf219c71a72360caf7bce311a2955d4a345be265756b01604a5bca50d9a4fc8 has active endpoints
```

```sh
CLI Version:              0.80.7
Running Engine Version:   0.80.7
```

enclave dump results in empty directory

Platform: MacOS 13.4.1 (22F82) - M1Pro
Backend: Docker
```
Client:
 Cloud integration: v1.0.35
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:51:16 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.21.1 (114176)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:50:59 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
The result of `docker inspect 3af7fe2cde9c`
```json
[
    {
        "Id": "sha256:3af7fe2cde9c5b39631b53ba5ee79ec43c19a4051b07f5fd0bc244eea99fd8f3",
        "RepoTags": [
            "bbusa/ethereum-genesis-generator:capella"
        ],
        "RepoDigests": [
            "bbusa/ethereum-genesis-generator@sha256:01b143df001dc9e5144bf71eb90d0eaa77bdc235993fadb9ac8e302accd6f292"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2023-07-07T11:51:42.285142877Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "",
            "Volumes": {
                "/config": {},
                "/data": {}
            },
            "WorkingDir": "/work",
            "Entrypoint": [
                "/work/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "arm64",
        "Variant": "v8",
        "Os": "linux",
        "Size": 657028556,
        "VirtualSize": 657028556,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/c1258c615b1f18bfe36b4d03bea44e4ac310c3f38b1f7613f75cc99a58efb36e/diff:/var/lib/docker/overlay2/f3666caf31c237d678b1f344481431d41dfc8aecbc62084588cbb88e53af7b74/diff:/var/lib/docker/overlay2/23f3efa4aac0c463067ec770282d7f4b124ff7005deaa8c4808765705017001d/diff:/var/lib/docker/overlay2/d153417f715fa74748374230f29b3431256400163df00b22913dc4f2bcc439e1/diff:/var/lib/docker/overlay2/efff8e463cbd624391db8ebaed836ea8d5b9e1d7f1d5e8022ec40a005c5b9844/diff:/var/lib/docker/overlay2/027d08e41c9e46a9909b62c54eea1281e3b7f7734ca74ec9201e565e0356ae98/diff:/var/lib/docker/overlay2/df4230c116f41a6e9cce57d340beaf7eae72b5174f02243190d944ed3b2a241e/diff:/var/lib/docker/overlay2/69dc588075d80e66f2ed417ee1985a5dc51a034aa4854d3a2ac87cb510e2451b/diff:/var/lib/docker/overlay2/97794a4f76d04722e3bd056ad77d8b640ff865c1178335262c1b0a58110a4751/diff",
                "MergedDir": "/var/lib/docker/overlay2/79b0edb417a3c7d981f6214acbc6e6e2a8a12a6af4176b7956d655d76220f796/merged",
                "UpperDir": "/var/lib/docker/overlay2/79b0edb417a3c7d981f6214acbc6e6e2a8a12a6af4176b7956d655d76220f796/diff",
                "WorkDir": "/var/lib/docker/overlay2/79b0edb417a3c7d981f6214acbc6e6e2a8a12a6af4176b7956d655d76220f796/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:42f253cd68b44bef697e08c3510860cda98a30b247efe4a60e4134f45ca44e14",
                "sha256:4406fa0bd5168eeea7e6cd5bce8900a5f4ecd1cfb2ec41068416f0809c403aac",
                "sha256:41f62963a5130ded506ddbf4330d7621d17df51efe2ebe1e11100f435c0ab001",
                "sha256:ce5a5dc49db12dc8a82bbc5f43dfc0b6d7ebb1e87eec8e627a514fac707f9990",
                "sha256:234522eebe150764b41dcce8f5146c5eaf929e8d60defc2358b60cdac3705461",
                "sha256:eff9f8101f63a76a198e89c1d652927b93101c3c2a25a5dde4cdca0e26d8e362",
                "sha256:f2a3513da19314974f98957ec02d583c8e1c966812baf80faf25a49acca828bd",
                "sha256:6cbb70a3397b396b2603954db3c912e4e17db2de549f2ffa2f15aa7148672f66",
                "sha256:370e5fe8eb882e1a0ccb96570aa16c848bc23deb5e9f5577c76855f8b8e52a85",
                "sha256:66528cdd65d74053d35b17fb4463989c3b75f638ef9bee50969d630312d835d7"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```
`docker network inspect acf219c71a72360caf7bce311a2955d4a345be265756b01604a5bca50d9a4fc8`
```json
[
    {
        "Name": "3afd98ccccdb4e718121ca5c1be521a0",
        "Id": "acf219c71a72360caf7bce311a2955d4a345be265756b01604a5bca50d9a4fc8",
        "Created": "2023-07-07T13:33:53.28813242Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.16.1.0/24",
                    "Gateway": "172.16.1.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.driver.mtu": "1440"
        },
        "Labels": {
            "com.kurtosistech.app-id": "kurtosis",
            "com.kurtosistech.enclave-creation-time": "2023-07-07T13:33:53Z",
            "com.kurtosistech.enclave-id": "3afd98ccccdb4e718121ca5c1be521a0",
            "com.kurtosistech.enclave-name": "yomamma",
            "com.kurtosistech.guid": "3afd98ccccdb4e718121ca5c1be521a0",
            "com.kurtosistech.id": "3afd98ccccdb4e718121ca5c1be521a0",
            "com.kurtosistech.is-network-partitioning-enabled": "false"
        }
    }
]
```

config.json:
```json
{
  "participants": [
    {
      "el_client_type": "geth",
      "el_client_image": "ethpandaops/geth:4844-devnet-6-990e113",
      "cl_client_type": "lighthouse",
      "cl_client_image": "ethpandaops/lighthouse:boxed-blobs-d534ac0"
    },
    {
      "el_client_type": "geth",
      "el_client_image": "ethpandaops/geth:4844-devnet-6-990e113",
      "cl_client_type": "teku",
      "cl_client_image": "consensys/teku:develop"
    },
    {
      "el_client_type": "geth",
      "el_client_image": "ethpandaops/geth:4844-devnet-6-990e113",
      "cl_client_type": "prysm",
      "cl_client_image": "ethpandaops/prysm:deneb-devnet7-e60b3bb,gcr.io/prysmaticlabs/prysm/validator:stable"
    }
  ],
  "network_params": {
    "deneb_fork_epoch": 3
  },
  "launch_additional_services": true,
  "wait_for_finalization": false,
  "wait_for_verifications": false,
  "global_client_log_level": "info"
}
```
Git commits:
https://github.com/barnabasbusa/eth2-package/commit/958622cd0a4ee10be7902e31e670ee5a4f77e380
https://github.com/barnabasbusa/eth-network-package/commit/1a65facd4e5b4f03f7ad7d1dde67aebac8ce634a

To start up I have used the following command: `kurtosis run --enclave yomamma github.com/barnabasbusa/eth2-package "$(cat ./example.json)"`

### Desired behavior

Enclave should be stopped and force removed.

### What is the severity of this bug?

Painful; this is causing significant friction in my workflow.

**Comment by h4ck3rk3y** [comment] 2023-07-07 14:03
Plus +1'ing this as something I ran into this last night as well on 0.80.7 on M1

**Comment by h4ck3rk3y** [comment] 2023-07-07 14:15
This was started using

`kurtosis run --enclave yomamma github.com/barnabasbusa/eth2-package "$(cat ./example.json)"`

**Comment by leoporoli** [comment] 2023-07-07 20:15
I run this: ...
```
kurtosis run --enclave yomamma github.com/barnabasbusa/eth2-package "$(cat ./example.json)"
kurtosis enclave rm {enclave-id} -f
```
... 4 times without any error, so I wasn't able to reproduce the issue.

@barnabasbusa commented us this on the Kurtosis Ethereum channel:
_Keep in mind, I wasn't able to reproduce_
_ok, so I think I know what the issue was_
_I think my docker app ran out ram, and I had to force close the docker container, just when I was also killing the enclave_

I'll close this issue for these reasons, but @h4ck3rk3y and @barnabasbusa you guys can re-open it if you reach out same problem again and can detect how to reproduce it. This is important because it takes several minutes and machine resources to reproduce the context.

**Closed as completed by leoporoli** 2023-07-07 20:15 UTC
Labels: bug, painful

**Comment by barnabasbusa** [comment] 2023-07-07 21:12
What would you recommend in terms of actually getting rid of that enclave? As it's still present there, and still can't seem to remove it.
