### ISSUE TITLE
Docs: Add code examples per supported language, via tabbed display containers, for the runtime SDK

### ISSUE THREAD

**Issue by galenmarchetti** [kurtosis-tech/kurtosis#1338] opened 2023-09-19 14:00 UTC
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/next/runtime-sdk-reference

### Issue description

It's difficult to translate the language-agnostic SDK description to language-specific code by reading the docs - as an end-user, I'd find it immensely useful to have code examples to see in my specific language so I can understand how to use the runtime SDK.

Design inspiration:
- Stripe's SDK docs per supported client library: https://stripe.com/docs/api/balance/balance_retrieve?lang=node

**Comment by leeederek** [comment] 2023-09-19 14:09
Closing as duplicate of #1283

**Closed as completed by leeederek** 2023-09-19 14:09 UTC
Labels: docs
