### ISSUE TITLE
Add docs on `kurtosis context set/ls`

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis#1880] opened 2023-12-01 16:20 UTC
### Where did you see the issue in our documentation?

https://docs.kurtosis.com/cli

### Issue description

@chunha-park pointed out that we don't have docs on `kurtosis context ls/set`!

**Comment by leeederek** [comment] 2023-12-05 14:49
Duplicate of: https://github.com/kurtosis-tech/kurtosis/issues/1536

**Closed as completed by leeederek** 2023-12-05 14:49 UTC
Labels: docs
